"""add weekly reports table

Revision ID: 550c5da3795c
Revises: fe65d246083a
Create Date: 2026-05-04 09:21:04.717307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '550c5da3795c'
down_revision: Union[str, None] = 'fe65d246083a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weekly_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('week_start', sa.DateTime(), nullable=False),
    sa.Column('week_end', sa.DateTime(), nullable=False),
    sa.Column('completion_rate', sa.Integer(), nullable=True),
    sa.Column('prev_completion_rate', sa.Integer(), nullable=True),
    sa.Column('best_category', sa.String(), nullable=True),
    sa.Column('worst_category', sa.String(), nullable=True),
    sa.Column('total_completed', sa.Integer(), nullable=True),
    sa.Column('total_tasks', sa.Integer(), nullable=True),
    sa.Column('streak', sa.Integer(), nullable=True),
    sa.Column('on_track_status', sa.String(), nullable=True),
    sa.Column('ai_recommendation', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weekly_reports_user_id'), 'weekly_reports', ['user_id'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_weekly_reports_user_id'), table_name='weekly_reports')
    op.drop_table('weekly_reports')
    # ### end Alembic commands ###
