"""Add email preferences and timezone

Revision ID: ea958bc4a625
Revises: f15597be4c69
Create Date: 2026-04-29 04:12:50.532593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea958bc4a625'
down_revision: Union[str, None] = 'f15597be4c69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_tasks', sa.Column('reminder_sent', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('timezone', sa.String(), nullable=True))
    op.add_column('users', sa.Column('email_notifications_enabled', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('email_morning_enabled', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('email_evening_enabled', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('email_events_enabled', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('email_plan_changes_enabled', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('morning_email_time', sa.String(), nullable=True))
    op.add_column('users', sa.Column('evening_email_time', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'evening_email_time')
    op.drop_column('users', 'morning_email_time')
    op.drop_column('users', 'email_plan_changes_enabled')
    op.drop_column('users', 'email_events_enabled')
    op.drop_column('users', 'email_evening_enabled')
    op.drop_column('users', 'email_morning_enabled')
    op.drop_column('users', 'email_notifications_enabled')
    op.drop_column('users', 'timezone')
    op.drop_column('daily_tasks', 'reminder_sent')
    # ### end Alembic commands ###
